### ISSUE TITLE
Lost block.db for osd. Can we used Vampyr for data extraction?

### ISSUE THREAD

**Issue by Alexeika2** [fbausch/vampyr#1]
Good day to you!

Firstly i want to thank you for developing such tool for forensic analysis of Ceph BlueFS.

My main question is there any theoretical possibililty to extract particular PG from osd which block.db device has been lost? What particular methods of Vampyr project tool may help to resolve our accident?

**Comment by fbausch** [comment]
I guess, if the RocksDB database is lost because the DB device is lost, the PG cannot be recovered. Most PG data is stored in the DB.
